name: smoknet-env
channels:
  - conda-forge
  - defaults

dependencies:
  - r-base=4.3
  - r-tidyverse
  - r-pacman
  - r-devtools
  - r-janitor
  - r-cowplot
  - r-ggbeeswarm
  - r-patchwork
  - r-viridis
  - r-ggridges
  - r-ggnewscale
  - r-magrittr
  - r-zeallot
  
  - python>3.9
  - pandas
  - scikit-learn
  - numpy
  - igl
  - matplotlib
  - pywavelets
  - networkx
  - ipython
  - ipywidgets
  - jupyterlab
  - jupyter_contrib_nbextensions
  - jupytext
  - nodejs

  - liblapack
  - libblas
  - openblas
  - lapack


# specified here: https://github.com/sealx017/RCFGL?tab=readme-ov-file
